### ISSUE TITLE
Question about player specific recipes?

### ISSUE THREAD

**Issue by jordsta95** [stanhebben/MineTweaker3#126]
Hey Stabhebben, I know you are working on this feature and I just wondered how this feature would work, as I am thinking of doing a troll recipe for a few people who are playing a pack of mine, and I wondered if something like the following would be posslble:
recipes.addShaped([if MobiusRex, troll1, if PrimalDemon, troll 2, else, woodPlank * 2,[[s,s,s],[s,s,s],[s,s,s]]);

And that would mean that the 2 players when crafting a simple recipe would get a troll.
Also, if this is possible, would player specific recipes show in NEI, e.g. MobiusRex would see troll1 and not woodPlank or would they see what should be seen by everyone?

**Comment by jaredlll08** [comment]
This isn't really possible, since server wise, there is no player, if there is no player, then the recipe will not be added, since the recipe will not be added the client will not be able to make the recipe. But it is a good idea, also I have looked into this myself on a different mod, and the only way for it to work, would be requiring a custom crafting handler, which checks the user's name, much like how rwtema does the peaceful recipe for the watering can
