### ISSUE TITLE
Localizations ending in '.name'

### ISSUE THREAD

**Issue by MarshMilo100** [stanhebben/MineTweaker3#199]
When i tried to change the localization of a golden nugget to something else, the name appears as the name ending with '.name'.

i am using minetweaker version 3.0.9C for 1.7.10

**Comment by hron84** [comment]
@MarshMilo100 could you please provide the code snippet you tried to use? I did few tries, and I did not see issue like this. Also, I recommend you to use triple backtick to fence the snippet.

**Comment by MarshMilo100** [comment]
Game.setLocalization("item.hqm:quest_book_0","The Quest Book Of Grimace");

**Comment by MarshMilo100** [comment]
It has the the name I set with just a '.name' on the end of it

**Comment by stanhebben** [comment]
In the log, it reports the key with .name. That's because internally, the key for the localized name has .name appended to the internal block name. This is not a bug, it's how it works, so don't be confused by the log output. There exist blocks that don't follow this convention (apparently) and it's those that have issues setting block names and localizations.

**Comment by jaredlll08** [comment]
seems to be resolved
