### ISSUE TITLE
MineTweaker drops logs all around the place.

### ISSUE THREAD

**Issue by AnrDaemon** [stanhebben/MineTweaker3#201]
There's a directory called "logs".
Please use it for what it is called for.

**Comment by jaredlll08** [comment]
The logs directory can get extremely cluttered, for instance,  my Fluxed-Crystals log directory has 482 files, and my Astrea~Infinitum log directory has 390 files (and that hasn't even been released yet, to give a reference of how cluttered stuff gets)
so by putting it in an easy to find place, it makes it easier.

**Comment by AnrDaemon** [comment]
You're kidding me? If YOUR logs directory is cluttered, it's your and only your problem.
My logs directory only have five files tops.
Chasing log files all around the file system is the least entertaining administration task.
I disagree with your judgement on the issue.

**Comment by jaredlll08** [comment]
logs are so small that I don't feel a need to delete them
482 logs is only 4Mb.
Also I am pretty sure @stanhebben had a reason for this.
but if you insist... I'll reopen

**Comment by jaredlll08** [comment]
The log file will stay where it is. People already don't upload it, so by moving it, we will have to add an extra step, and it will confuse people who are used to the old log file location.

**Comment by AnrDaemon** [comment]
*facepalm*

**Comment by jaredlll08** [comment]
No one else has complained,  literally no one,  you are the only one with
this 'issue' and it will confuse other users because the old log will
stay,  and they won't know which one to upload. Also I don't see you go
complaining to Mojave that their options.txt isn't in a configuration
folder...

**Comment by AnrDaemon** [comment]
> Also I don't see you go complaining to Mojave that their options.txt isn't in a configuration folder

I did. Their answer was exactly the same: "It was there for years, why should we change it?"
Should I express, what I think of such answers, or can you construct it by yourself?

**Comment by jaredlll08** [comment]
Look,  I am sorry that you have a problem with this,  but the pros and cons
list looks like this so far...

Pros for having it where it is right now:
1) users know where is it
2) it is easy to find
3) the logs folder gets cluttered a lot
4) there has only been a single complaint in over 100 issues.

Cons of having it where it is right now:
1) AnrDaemon is unhappy with where it is

Pros for moving it to the log folder
1) AnrDaemon is happy
2) a log file is in the log folder

Cons for moving it to the log folder
1) the existing file will still be there,  causing confusion for users,
since they will just look at that file,  which would now never change
2) users won't know where it is
3) we would have to ask users what Mt version they are using to direct them
to the file.
4) the logs folder will get cluttered since a new log is created every time
you start the game,  causing 200+ logs in the folder which will be hard to
navigate (YOU may clean the folder,  but the majority of users do not)

**Comment by AnrDaemon** [comment]
I perfectly understand all of your outlined reasons. I'm not going to a second round of this discussion, the issue is already closed by you.
