### ISSUE TITLE
I will adding the missing machines in my mod

### ISSUE THREAD

**Issue by Dream-Master** [stanhebben/MineTweaker3#234]
@stanhebben 
@jaredlll08 
I testing now the Version 3.10. Now there is no Gregtech support any more. My GT addon mod only adding the missing machines and not replacing the exiting ones like the assembler, alloy smelter etc you adding before.
It would be better to include gregtech support in the Minetweaker mod itself and when i adding some machines (maybe for Gregtech unofficial Version) i make a pull request. It makes my mod useless but i dont care because i only made this mod because i need fluid support.

**Comment by Dream-Master** [comment]
You can see in my source what i add.

https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon

**Comment by Dream-Master** [comment]
bculkin2442 did a good Job adding most of the machines.
Only the Distillation Tower from unofficial Gt and the new Arc and Plasma Arc furnace liquid support is missing but those i can add.

**Comment by Yulife** [comment]
Native GT support was removed. [Source](http://minetweaker3.powerofbytes.com/wiki/Changelog)

Stan even mentions that you now have the support :)

**Comment by Dream-Master** [comment]
I can add the missing machines too and separating Gretech. Merging bculkings and my code in my mod

**Comment by jaredlll08** [comment]
So this can be closed?

**Comment by stanhebben** [comment]
I can provide you the source code for the remaining machines, so you don't have to write it all over again.

**Comment by stanhebben** [comment]
If you want to maintain GT support through PRs, that's fine for me. I can readd it and release a new version with your updates as soon as they're PRed in.

**Comment by Dream-Master** [comment]
I try to merge the code today if it work i will close the issue. If not we have to find another solution.

**Comment by Dream-Master** [comment]
Ok first test Version are available.
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/releases/tag/1.0.0

**Comment by Dream-Master** [comment]
Ok support added.
https://www.dropbox.com/s/u7h8e5uosjrlnwv/GTTweaker-1.7.10-1.0.1.jar?dl=0

**Comment by Yulife** [comment]
Wenn du dass Wiki updatest achte bitte darauf den gleichen Stil zu benutzen wie andere alle das machen. Schau mal den Unterschied zwischen [dem IE Support Stil](http://minetweaker3.powerofbytes.com/wiki/Mods:Immersive_Engineering_Support) und [deinem Gregtech Support Stil](http://minetweaker3.powerofbytes.com/wiki/Mods:GregTech_Support)

Oben ist eine Überschrift die sagt "Handlers Supported" und dann schreibst du eben die Handler die du hast. Du solltest auch jede deiner Parameter mit der @Optional annotation rot markieren (steht im Beispiel), nämlich in der Zeile die mit "//" anfängt, dazu gleich mehr. In der Documentation wird nicht mit imports gearbeitet (frag mich nicht warum, ist einfach so) also bitte schreib die ZenMethod Beispiele voll aus [z.B. mods.gregtech.Packer.addRecipe(output, input1, input2, durationTicks, euPerTick); ]
Du schreibst die Parameter einfach in was die machen auf obwohl du eigentlich Beispiele hinschreiben solltest die:

1: Sinn machen

2: Sofort funktionieren sobald du sie in die eigene Script ingame reinkopierst

Ganz oben steht außerdem der Name der ZenClass.
Über jedem Handler steht eine Linie markiert mit "//" am Anfang die die Parameter der ZenMethod zeigen. [z.B. //OutputStack, InputStack1, InputStack2, Time in Ticks, EuPerTick ].
Danach kommt dann eben die funktionierende Scriptzeile [z.B. mods.gregtech.Packer.addRecipe(<minecraft:dirt>, <minecraft:diamond>, <minecraft:emerald>, 10, 25); ].

**Beispiel:**
```
== Handlers Supported ==

The following handlers are supported:
* Packer

Each of these handlers can have recipes added or removed:

 Parameters marked as <span style="color:red">red</span> are optional and can be left out
 
 //Packer
 ////OutputStack, InputStack1, InputStack2, Time in Ticks, EuPerTick
mods.gregtech.Packer.addRecipe(<minecraft:dirt>, <minecraft:diamond>, <minecraft:emerald>, 10, 25);
```

----------------------------------------------------------------------------------------------------------
If anyone is wondering what that means, I am just explaining the correct style of the MT Wiki to @Dream-Master because his style is off.

**Comment by Yulife** [comment]
I see many of your machines have an InputStack2, wouldn't you be able to make those ```@Optional```?

**Comment by Dream-Master** [comment]
@Yulife Ich hab nur das übernommen was Stan gemacht hab. Ich hab mal ein wenig heute in die Formatierung reingeschaut bin aber erstmal froh das der Mod läuft.
Alle Feinheiten, Fixes und die Dokumentation werden langsam folgen.
Ich hab versucht soviel wie möglich zu ändern. Das mit den optionalen Stacks muss ich mal schauen wie das geht. Nehme gerne pull requests entgegen. 
Danke für die Hilfe meld mich wenn ich fragen habe.

Thanks Yulife for your help.

**Comment by Yulife** [comment]
Kein Problem, immer da zu helfen! Ja, eigentlich machen dass die meisten mit dem '''@Optional''' wenn nur ein InputStack gebraucht ist, wie z.B. bei der Refinery von Buildcraft. Dort kann man z.B. Öl in Diesel raffinieren aber mit Minetweaker kann man auch ein zweiten InputFluid machen, z.B. um Wasser und Lava zu Öl zu raffinieren. Dies erleichtert den User weil er oder sie nicht dann "null" anstelle vom zweiten InputFluid machen muss. Ich würd eine Pull Request machen aber leide habe ich keine Ahnung von Gregtech-API und wie es funktioniert, gar ob es beide InputStacks braucht oder nur eins. Viel Glück!

**Comment by Yulife** [comment]
[I edited a few things and added a note to each of them](http://minetweaker3.powerofbytes.com/w/index.php?title=Mods:GregTech_Support&action=history)

**Comment by Dream-Master** [comment]
@Yulife 
Vorher war das aber Übersichtlicher. Da kriegt man ja Augen Krebs wenn ich mal alle Gregtech Maschinen hinzugefügt hab. Ich nutze auch das Wiki auch und so finde ich nix. Bei Imersive Engeneering gibt es nur ein paar Maschien Gt hat aber viel mehr.
Ich mach mal so weiter und wenn ich fertig bin kann man das ja nochmal überarbeiten.
Mein github Wiki
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/wiki

Gibt es eine schrift die ein wenig kleiner aber größer als die Rezepte Schrift für die jeweiligen Maschinen?

**Comment by Dream-Master** [comment]
@Yulife 
So hab was gefunden so würde ich weiter machen wollen.

**Comment by Yulife** [comment]
Na und? Das selbe musste ich mit Mekanism machen. Braucht eben seine Zeit. Wenn alles ordentlich ist wird sicherlich nichts Augenkrebs verursachen :)

**Comment by Dream-Master** [comment]
Ja gut wenn das nicht übersichtlich für dich/euch ist dann weiß ich nicht. Ich mach das fertig und dann kannst du es ja formatiere wie es für dich/euch gut ist. Ich hoffe ich schaffe es diese Woche das fertig zu mach.
Das Wiki auf github ist für mich.

**Comment by Yulife** [comment]
Wenn du meinst. Damit erschwerst du die Sache eigentlich nur.
