### ISSUE TITLE
Script Problems

### ISSUE THREAD

**Issue by masquerade5430** [stanhebben/MineTweaker3#286]
Hey guys! I'm not sure if I should post this here, but I'm having some difficulties with my script. I posted on the forum, but nobody has replied. Could any please tell me what's wrong?
http://minetweaker3.powerofbytes.com/forum/viewtopic.php?f=4&t=722&sid=6ec7d59609d4874cf139202c32fb991a

**Comment by Blue64** [comment]
For starters, your furnace output is using a variable, which is totally NOT recommended if I recall correctly. All it takes is 1 ingot to be out of sync with it's paired dust or it's ore, and the issue compounds from there, as everything past it will also be off by 1 (for example, if you don't have any form of Gold Dust, anything beyond Gold Ore in the list would give you an Ingot different from it's Dust, I think).

I also do not see any section BEFORE the unification where it adds those OreDict entries. Also, if you unify "ore", would you still need to unify the "oreNugget", "oreIngot", etc also? Because I notice that too.

Actually I see the entire script is like that with it's variable output. Also, you won't nail all the recipes in NEI if you only do
" recipes.removeShaped(oreIngot * 9, [[oreBlock]]);"
I have no idea how to do the code tag, but you need to include the null options as well, otherwise you'll miss ones that are shaped:
Null, null, null
Null, oreBlock, null
Null, null, null
As some mods have been known to do stuff like that, I had that issue with M-Ore's Sword recipes for example, had to remove it all 3 Shaped possibilities, just to make sure I got it. I'm curious how they got liquids to be recognised, as I've been waiting for a response on [that](#150) for almost a month now 

I honestly have no idea how the NEI.hide works, but I do recall seeing something about it on the [wiki](http://minetweaker3.powerofbytes.com) [somewhere](http://minetweaker3.powerofbytes.com/wiki/Mods:NEI_Support)

I would try putting the OreDict section BEFORE the unification, I actually currently still have mine in Separate Files. I'm still using v3.0.9C and it loads in Alphabetical Order, so if you name the OreDict "a - OreDict.zs" then it'll load before "Ore Unification.zs", or even "Berries.zs"…or you can just move it below the var/val section.

On a similar note, I'd look over those unifications carefully and see if there's anything you don't need, such as "realIngot", I do not see that anywhere except during Unification.

The best advice would be to take a long hard look at every part of the script and decide if it's what you want, and if it's needed, as sometimes one issue can create another, and if it's not something you want, then you'll probably want to get rid of it.

Another good piece of advice: ALWAYS double check the end of line Semi-Colons! "extra steel blocks" is missing it's close bracket AND semicolon, also you may wish to look into removing the "withTag" section of the TConstruct:potionLauncher

**Comment by masquerade5430** [comment]
Yeah I got this script from a reddit user, but I have decided to use a different script to fix what I want. Thanks for taking the time to look at it though.
