### ISSUE TITLE
request commands

### ISSUE THREAD

**Issue by anar4732** [stanhebben/MineTweaker3#296]
request commands:

<mod:item>.texture_front = "texture":
<mod:item>.texture_top = "texture":
... and more

and support special characters {Ş Ö Ü} ... and like

**Comment by Blue64** [comment]
are you referring to something similar to [THIS](http://www.curse.com/mc-mods/minecraft/226447-resource-loader)? Special Characters would be nice, except MineCraft it's self needs to recognize them first, and then they need to be used to reference a valid object (eg ```<minecraft:iron_ingot>``` or ```<fluid:water>```) the only reason I could think you might need any further characters would be if it is used as a ```val``` or ```var``` and the parser isn't recognizing it, which wouldn't need MineCraft to recognize it as it never gets read by MineCraft.

**Comment by skydark** [comment]
If you want to use unicode characters in strings(like `tnt.addTooltip("☞♪");`) and/or comments, I have sent a pull request( #285 ). It is possible to support unicode characters in variable names with the same approach.
Although, it is better to use resource loader approach if you want to localize tooltips/nbttags/... The only problem is #242 .

**Comment by anar4732** [comment]
important:

<minecraft:crafting_table>.texture_front = "minecraft:stone.png";

this code you should do like the stone in front of the view craftin_table

--------------------------------------------------------------------------------------------------

in the name of the item {Ç Ş Ü Ö Ğ} error seems like characters
 { invalid character }

--------------------------------------------------------------------------------------------------
please update the mod

I am Mod_Pack developing

thanks...

@Blue64 @skydark

**Comment by PrincessRTFM** [comment]
@skydark I'm using MineTweaker 3.0.10b, and I can put `§` into tooltip/name strings with no problems. (Tried it first in names to format them, since I can't use the format.* functions with names, only tooltips.)

**Comment by skydark** [comment]
@PrincessRTFM That's because `§` is encoded as 0xa7, which is smaller than 0xff. Try something like `Ğ`, `你好`, `☞♪`, `Я　чайка`, `愛衣` instead.

**Comment by anar4732** [comment]
ALSO
Please Add:

recipes.remove(<flansmod:*>);
/remove all flansmod recpies

**Comment by Blue64** [comment]
@skydark not to mention ```§``` if I'm not mistaken is also used repeatedly (and rampantly) throughout the MineCraft File System, as well as the various references to the ```.class``` files used to compile the ZenScript into a format that is applicable to MineCraft

@anar4732 THAT is a good idea! Although you'd most likely actually want
```
// Multiple Recipes.Removing(FlansMod:Item:Meta)
recipes.remove(<flansmod:*:*>);
# Don't forget the <> because it's referencing the IItemStack, or IIngredient, which needs <>
# IFluidStack is a different command
// <fluid:water>
```
to ensure you get them all, unless you only desired to remove meta 0 of all items within a mod (quite ineffective for ```Applied Energistics 2```!). Although, in theory, the Dev should really anticipate such issues in code discrepancies.

on a related request:
```
// Mod Specific Wildcard Removal WITH Specific MetaData
recipes.remove(<flansmod:*:16>);
# only removes recipes from FlansMod with meta of 16 as result [eg, Dyed Black]

// Mod Specific Wildcard Removal minus Meta, treating Meta as a Wildcard (anar4732's Idea)
recipes.remove(<flansmod:*>);

# ... I had some other idea, but forgot it before I could type it. -.-'
```

**Comment by anar4732** [comment]
Please Update the mod

**Comment by jaredlll08** [comment]
Please learn to be patient, we(the developers) actually have real lives. From this point in, if I see anyone ask for a release / a new version I will delay my work on it for an hour.

To go through the issues here:
- [ ] output texture names | will cause issues with items with metadata as item metadata can go up very high
- [ ] special characters | @skydark has done these already, Stan seems to be MIA, I will try and speak to him about giving me perms to release the mod and accept pull requests
 - [ ] *IF* you had actually done some research into the issues, which it is obvious that you did not you would have found #251 which is exactly what you are asking for, however, the response to that is, you can do it yourself by using itemstack arrays and loops

**Comment by anar4732** [comment]
Please add an update with the following command
this is very necessary for me


```javascript
recipes.remove(<Mod:*:*>);
```

@jaredlll08

**Comment by jaredlll08** [comment]
Congratz! I am now NOT touching minetweaker until 2016, I hope you are
happy.

**Comment by anar4732** [comment]
@jaredlll08 
do as you see fit...

I am mod_pack developing
too much trouble to be individually set

**Comment by jaredlll08** [comment]
You still don't understand though, DEVELOPERS HAVE LIVES! The things that are currently going on in my life right now are:
Moving Houses, packing boxes up and just general strees
Laptop SSD got corrupt, aka I had no laptop for a bit
I'm on holiday, using all of my free time to relax, coding is not relaxing
Dealing with both of my routers getting struck by lightning, having to setup a new one.

Also not to mention that your DEMAND (at this point, you are demanding it, not asking, demanding) is invalid as it has already been requested, AND a work around was given. I have also looked into this, in my precious free time and it is not so easy due to how minetweaker gets items.
So get off your high horse, I don't care if you are "mod_pack developing", others are also doing it, it doesn't make you special, you will wait for the issue to be solved like the other people.

**Comment by anar4732** [comment]
@jaredlll08 
OK! ok...
do as you see fit..

**Comment by PrincessRTFM** [comment]
@jaredlll08 Good luck with the laptop and routers! I know stuff like that isn't very relaxing either, so I hope it gets solved soon so you can enjoy your vacation.

**Comment by Blue64** [comment]
@jaredlll08 How do you have 2 routers get struck by lightning? Did you have someone throw an EvilCraft Lightning Grenade at them or something?  Lol that's horribly unlucky. I had no idea you had your laptop go kaput, I feel for ya man, data corruption is a royal pain. And moving on top of that can't be too easy either.

I was unaware that it was not possible to wild card a removal because of that though.

@anar4732 did you miss the entire post where I said exactly what you requested? If you constantly bug a person to do something, there comes a point where you're getting in the way of them doing it, because they're too busy responding to you.

P. S. I'm developing a ModPack too (personal so far, gotta get the mods to play nice on launch before I go looking for any permissions), but you don't see me in here begging for an update, instead I'm trying to help where I can by utilizing what I do know to help with the small stuff (such as one guy who ```mirrored``` his ```OreDict```, then did ```AddAll```, thus creating an error, you ```Add```, then ```Mirror```, not ```Mirror``` then ```Add```), because if I can solve it, then he won't need to spend his valuable time answering the small stuff, and instead he can relax, or he can Code this mod some (for ***FREE*** I might add), and this is all on top of any actual ***WORK*** he actually has, or any other life events (moving, fried electronics, holidays, etc), and let's not forget, he probably also would like to play MineCraft every once and a while.

**Comment by jaredlll08** [comment]
@Blue64 I honestly have no idea, but I have some theories, so I use a modem as a wifi extender, since the main modem is useless at wifi, but has a nice UI, the second is amazing at wifi, but terrible UI, so 
$Main = Modem 1
$Other = Modem 2

$Main was plugged in, but we recently got an electrician to fix the power extension there, and we have had no problems since.
$Other is connected to $Main via a 50 meter Ethernet cord ran through the roof, so I was playing ps4 in my brothers room where $Other is, and suddenly, the TV goes black for about 5 seconds, and I lose connected, $Other is boiling hot, $Main is fairly hot, so my theory is, $Other got his, then send a huge packet or something through the Ethernet line, which in turn fried $Main.

If I am just completely wrong about how this works, please tell me xD

Also thanks for all the help @Blue64 I have been meaning to thank you for basically running this whole issue tracker recently =D

Also I don't even remember the last time I properly played MineCraft >_<

**Comment by Blue64** [comment]
@jaredlll08 about a month, maybe a month and a half on my end cause I can't even get the mods to launch MineCraft lol

It could have been a huge packet, but that wouldn't suddenly overheat, it's more than likely that the Ethernet cable acted as a conductor, so when $Other got hit, it spread to $Main. Another possibility is that it had bad cooling (metal surface helps, wood not so much, and always try to maintain airflow, aim a fan at it if you can, as this will limit it's maximum possible temp also. Remember: there is no such thing as "```Cold```", only "```Lack of Heat```" ```;)``` Heat always wants to fill in the Cold, metal allows for fast thermal transfer (and electric lol), hence it's use in AC units, and refrigerators (copper is one of the most popular due to efficacy))

I just help where I can ```^_^'``` it helps that I've been going over everything that I possibly can because I've been patching up all these mods' Cross-Compatibility lol (```Aluminium``` & ```Aluminum```, various ```<ore:>``` recipes, tweaking the difficulty of everything under the sun and moon (and the Random Things 2 Blood Moon lol, it won't respect the Spawn Rules, but fear not, the angry horde will despawn at sunrise! ProTip: Hide in ```Minas Tirith```.), and setting up the config files every time I update a mod (for various reasons, mostly compatibility)), I'm getting close to completing it enough to get back to [indexing my ZenScripts](https://github.com/Blue64/MT-ZenScript), but that's not quite all of the (200+) mods lol so I've got my work cut out for me.

I've also been poking around ```EvilCraft```, ```BloodMagic```, & ```MystCraft``` (been trying to get an Instability Corruption Mod updated to 1.7.10 but they claim the API is incomplete ```*rolls eyes*```), amongst a few others.

**Comment by anar4732** [comment]
when do you plan to update?
@jaredlll08

**Comment by PrincessRTFM** [comment]
when do you plan to stop asking for updates?
@anar4732

He'll update when he updates, and no sooner. No mod dev likes being asked that, and a lot of them will intentionally delay updating when people do so. Be thankful he spends his own free time working on something for other people as it is, and don't be greedy.

**Comment by jaredlll08** [comment]
@PrincessRTFM thanks for understanding unlike some people, who will momentarily be banned from MY minetweaker continuation. The ideas were not bad, the arrogance of the person who posted the idea is unbearable though.

**Comment by jaredlll08** [comment]
I'm unlocking this for now, since some of these are valid requests, however, please note, I (Notice I used the word "I", as in me, as in an actual human being that has other commitments in life) am currently in my last year of school, which is very stressful and has limited my coding time a lot. So these will come, but please don't ask for an eta.

**Comment by Blue64** [comment]
So, when is the ETA? ```:P``` jk, I hope school is easy for you @jaredlll08 ```:)``` I know what it is like for Real Life to get in the way, hang in there ```:)``` :+1:

**Comment by jaredlll08** [comment]
This isn't happening, especially with 1.9
