### ISSUE TITLE
[Request] Array var/val

### ISSUE THREAD

**Issue by karakufire** [stanhebben/MineTweaker3#328]
I want `var[]` and `val[]` identifier. I'm tired that `as IItemStack[]` or `as IIngredient[]` must follow `[foo, bar, baz,...]` to declare ItemStack var or val.  
`var foos = [<minecraft:apple>, <minecraft:gold_ingot>, <minecraft:diamond>] as IItemStack[];`  
turns  
`var[] foos = [<minecraft:apple>, <minecraft:gold_ingot>, <minecraft:diamond>];`

**Comment by jaredlll08** [comment]
Unfortunately we need the "as XYZ" to determine what array it is.

**Comment by karakufire** [comment]
why need these? I think these `as FOO` cause increasing unnecessary error from forgetting these.

**Comment by jaredlll08** [comment]
As I said before...
We need the "as FOO" to determine what type of array we are receiving. While YOU may know that it is an IItemStack array, unfortunatly the code is not smart enough to know what array it is, for example

var[] foos = [1,2,3,4,5]

That can be interpreted as an Integer array, however it can also be a Double array or a Float array.

**Comment by VariableVixen** [comment]
What about auto-expansion? Define it as the narrowest type (your example with the numbers would be defined as integers) and expand as needed. Possible, or a no go?

**Comment by jaredlll08** [comment]
While it is probably possible(note, I have not looked into any of this at
all, these are just general problems with it), however, people may do: 54.2
which can be a double or a float, also we would need to loop through the
whole array and decide what it is, and that will affect startup and reload
time.

**Comment by VariableVixen** [comment]
True, but it shouldn't be that much of an effect, at least for small(ish) arrays. Throw everything into an `Object` list, keep track of the "largest" (ie, most expanded) type seen, then copy everything from the `Object` list into a new list of the appropriate type...

Still, just because you can doesn't mean you should and all that. I haven't looked at the internals, so I don't know how easy, how simple, or how safe this would be to implement. Just some idle musings on the subject.

**Comment by jaredlll08** [comment]
After some thought, it would increase load time, which is already sub-par, so I may come back to this, but don't expect it soon
