### ISSUE TITLE
No Such Method Post Init

### ISSUE THREAD

**Issue by jredfox** [stanhebben/MineTweaker3#354]
CAPS = INPORTANCE

Version: MineTweaker3-1.7.10-3.0.10 
Crash Report: http://pastebin.com/aTBSiZgL
No Such Method Post Init. I also had modtweaker to but, it said nothing about modtweaker. Modtweaker's version is : ModTweaker2-0.9.5

**ImmersiveEngineering-0.7.7 CAUSED THE REFRESH TO HAPPEN NOT SURE IF IT CRASHED BECAUSE, MINETWEAKER DOESN'T HAVE A WORKING REFRESH HANDLER OR IF IT'S INCOMPATIBLE WITH THAT MOD.**

This happened when recreating every single tekkit ever made into one modpack 1.7.10. I hadn't even finished integrating tekkit ledgonds, I still have two more tekkits to go.  I don't usally crash the game but, when I do it won't stop crashing lol.

**Comment by Voidi** [comment]
Update your Minetweaker https://github.com/BluSunrize/ImmersiveEngineering/issues/661

**Comment by jredfox** [comment]
my minetweaker is up to date. you didn't even read the version?
MineTweaker 3.0.10 for Minecraft 1.7.10 it says on the website and that is what I have

**Comment by jaredlll08** [comment]
Ahem, maybe you should look on curse and tell us the latest version, then
look at your file and tell us what version that is.
And Hey, while you are on curse, you may as well download the actual latest
version being, 3.0.10B.

When people report issues to us, we read them fully, I suggest you do the
same(as in, read what Voidi posted).

my minetweaker is up to date. you didn't even read the version?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/stanhebben/MineTweaker3/issues/354#issuecomment-224727060,
or mute the thread
https://github.com/notifications/unsubscribe/AFS9xdANZkPco-u3hxtbgnNRXcbGmJ3Vks5qJy4-gaJpZM4IwlqV
.

**Comment by jredfox** [comment]
well then their website is outdated 
http://minetweaker3.powerofbytes.com/downloads.html

**Comment by jaredlll08** [comment]
Yea, only @stanhebben has access to the website, this has been the case (website being outdated), curse is the main download place currently.

**Comment by jredfox** [comment]
sorry got it.
