### ISSUE TITLE
Scripts not loading on joining server!

### ISSUE THREAD

**Issue by develman117** [stanhebben/MineTweaker3#357]
OK so when i join my server the script dont load, i have to do /mt reload every time i join.
im using the infinity mod pack expert mode.
in the log it says that the scripts have loaded but when i get in game the client side nei don't show up.
i added tool tips so every time i tip something like banned, or cheating it would should those items that are banned. or whatever.

**i know that someone already posted a similar issue before but i have not been able to fix my issue after reading it.** 
Please let me know what i can do to fix this.

**Comment by Yukigamine** [comment]
What version of the mod are you using?

## Do you have any scripts that change recipes which you can test to see if they work?

I am currently experiencing this (or a similar) issue on version 3.0.10B. (Infinity Evolved Expert 2.50).

On the surface it seems to be the same issue from #237, however after studying both client and server logs all of the scripts including my custom ones. The issues arises when each time the player joins the server where NEI will not show the new recipes (or in OP's case I'm guessing, the tooltips) until the scripts have been forced to reload by /mt reload.

I can open my own thread if this is a different issue but since it seems very similar I just replied here. Please let me know if there are any logs I can provide to help in the resolution of this issue. I am currently looking for other possible solutions to the issue and will post if I find any.

**Comment by develman117** [comment]
only things i have removed are the rftool dimlets.
and im using 2.5.0 infinity evolved expert, the latest version.

http://pastebin.com/VSF34Tva

**Comment by ExDomino** [comment]
I have the same issue, with FTB Infinity Evolved 2.5.0, and as we're using a modpack, it's not possible to downgrade or upgrade easily, nor to change anything client side. The only thing we could do is to run the command "/mt reload" in loop every single minute with a command computer from computercraft.

**Comment by develman117** [comment]
yeah i have tried that too.
at first i thought it was just scripts but even after reinstalling the whole pack it still don't work.

hope there is a fix for it soon.

**Comment by ExDomino** [comment]
There is no solution I'm afraid. Command computers cannot use "/mt reload" and this command is not recommanded. The only way is to install the script client-side, that is for many of us impossible!

**Comment by jaredlll08** [comment]
Do me a favour, load the game, join a server, send me the Game log (NOT the minetweaker log)

**Comment by develman117** [comment]
Here is the full game log.
https://www.mediafire.com/?sudr7mp3rhd102d
again im using 2.5.0 infinity evolved

**Comment by Voidi** [comment]
@develman117 Wait, what doesn't work? the recipe remove or didn't the banned items show up in NEI ?

**Comment by jaredlll08** [comment]
@develman117 
is that a log from:
Starting the game.
Joining a server (WITHOUT joining a client world first)
Log off
Close Game
Send me the log.
?

**Comment by develman117** [comment]
there is a way to get it working.
all you have to do is remove these 3 mods and it all works.
FTBTweaks 
FTBUtilities
FTBLib
